// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Api.Entities;

#nullable disable

namespace Store.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522100412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Store.Api.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5d24b61-9012-4cfc-a496-bf66d405785f"),
                            CategoryName = "Electronics & Gadgets"
                        },
                        new
                        {
                            Id = new Guid("1c02563b-5678-4321-951f-5063a8241b22"),
                            CategoryName = "Sports & Outdoor"
                        },
                        new
                        {
                            Id = new Guid("7d8e9f0a-1122-3344-5566-778899aabbcc"),
                            CategoryName = "Home & Living"
                        });
                });

            modelBuilder.Entity("Store.Api.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b11c22d3-44e5-55f6-66a7-77b88c99d0a1"),
                            CustomerAddress = "99/1 มหาวิทยาลัยธรรมศาสตร์ ถ.พหลโยธิน ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี 12120",
                            CustomerEmail = "nattapong.k@gmail.com",
                            CustomerName = "ณัฐพงษ์ แก้วมณี",
                            CustomerPhone = "081-234-5678"
                        },
                        new
                        {
                            Id = new Guid("e99d88c7-66b5-55a4-44f3-33e22d11c0b2"),
                            CustomerAddress = "456 คอนโดศุภาลัย ปาร์ค แขวงจตุจักร เขตจตุจักร กรุงเทพมหานคร 10900",
                            CustomerEmail = "pimonpat.s@outlook.com",
                            CustomerName = "พิมลภัส ศรีสุข",
                            CustomerPhone = "089-876-5432"
                        });
                });

            modelBuilder.Entity("Store.Api.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            CreatedAt = new DateTime(2026, 5, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("b11c22d3-44e5-55f6-66a7-77b88c99d0a1")
                        },
                        new
                        {
                            Id = new Guid("66666666-7777-8888-9999-000000000000"),
                            CreatedAt = new DateTime(2026, 5, 22, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("e99d88c7-66b5-55a4-44f3-33e22d11c0b2")
                        });
                });

            modelBuilder.Entity("Store.Api.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-b2b2-c3c3-d4d4-e5e5e5e5e5e5"),
                            OrderId = new Guid("11111111-2222-3333-4444-555555555555"),
                            ProductId = new Guid("f49341db-a1c2-403d-749c-08deb754c526"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-c3c3-d4d4-e5e5-f6f6f6f6f6f6"),
                            OrderId = new Guid("11111111-2222-3333-4444-555555555555"),
                            ProductId = new Guid("8a7b6c5d-4e3f-2a1b-0c9d-8e7f6a5b4c3d"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-d4d4-e5e5-f6f6-a7a7a7a7a7a7"),
                            OrderId = new Guid("66666666-7777-8888-9999-000000000000"),
                            ProductId = new Guid("2c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("d4d4d4d4-e5e5-f6f6-a7a7-b8b8b8b8b8b8"),
                            OrderId = new Guid("66666666-7777-8888-9999-000000000000"),
                            ProductId = new Guid("3e4f5a6b-7c8d-9e0f-1a2b-3c4d5e6f7a8b"),
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("Store.Api.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f49341db-a1c2-403d-749c-08deb754c526"),
                            CategoryId = new Guid("a5d24b61-9012-4cfc-a496-bf66d405785f"),
                            ProductDescription = "หูฟังไร้สายครอบหูระบบตัดเสียงรบกวนแบบ Active Noise Cancellation (ANC) มีไดรเวอร์ขนาด 40 มม. ให้เสียงเบสหนักแน่น แบตเตอรี่ใช้งานได้ยาวนานต่อเนื่อง 45 ชั่วโมงต่อการชาร์จหนึ่งครั้ง",
                            ProductName = "SoundWave Prime-X",
                            ProductPrice = 4990.00m
                        },
                        new
                        {
                            Id = new Guid("8a7b6c5d-4e3f-2a1b-0c9d-8e7f6a5b4c3d"),
                            CategoryId = new Guid("a5d24b61-9012-4cfc-a496-bf66d405785f"),
                            ProductDescription = "นาฬิกาอัจฉริยะหน้าจอ AMOLED ขนาด 1.43 นิ้ว รองรับการวัดอัตราการเต้นของหัวใจ ตรวจสอบคุณภาพการนอนหลับ และติดตามโหมดออกกำลังกายกว่า 100 โหมด มี GPS ในตัวและกันน้ำระดับ 5ATM",
                            ProductName = "AuraLink Smart Watch Series 5",
                            ProductPrice = 3290.00m
                        },
                        new
                        {
                            Id = new Guid("2c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            CategoryId = new Guid("1c02563b-5678-4321-951f-5063a8241b22"),
                            ProductDescription = "รองเท้าวิ่งมาราธอนระดับท็อป เสริมแผ่นคาร์บอนไฟเบอร์เต็มแผ่น ช่วยเพิ่มแรงส่งและรองรับแรงกระแทกได้อย่างยอดเยี่ยม ผ้าหน้าอัปเปอร์ระบายอากาศได้ดี น้ำหนักเบาพิเศษเพียง 185 กรัม",
                            ProductName = "ApexRun Pro Carbon",
                            ProductPrice = 6500.00m
                        },
                        new
                        {
                            Id = new Guid("3e4f5a6b-7c8d-9e0f-1a2b-3c4d5e6f7a8b"),
                            CategoryId = new Guid("1c02563b-5678-4321-951f-5063a8241b22"),
                            ProductDescription = "กระบอกน้ำสแตนเลสเก็บอุณหภูมิร้อน-เย็น เกรดพรีเมียม (18/8 Food-Grade) เก็บความเย็นได้นาน 24 ชั่วโมง และเก็บความร้อนได้ 12 ชั่วโมง ฝาปิดกันรั่วซึม 100% ความจุ 32 ออนซ์",
                            ProductName = "HydroPeak Insulated Flask",
                            ProductPrice = 1250.00m
                        },
                        new
                        {
                            Id = new Guid("4f5a6b7c-8d9e-0f1a-2b3c-4d5e6f7a8b9c"),
                            CategoryId = new Guid("7d8e9f0a-1122-3344-5566-778899aabbcc"),
                            ProductDescription = "เครื่องฟอกอากาศอัจฉริยะสำหรับห้องขนาด 35-50 ตร.ม. มาพร้อมไส้กรอง True HEPA H13 ดักจับฝุ่นละอองขนาดเล็ก PM2.5 และสารก่อภูมิแพ้ได้ถึง 99.97% ทำงานเงียบสนิทเพียง 22 เดซิเบล",
                            ProductName = "PureAir Breeze V2",
                            ProductPrice = 3990.00m
                        },
                        new
                        {
                            Id = new Guid("5a6b7c8d-9e0f-1a2b-3c4d-5e6f7a8b9c0d"),
                            CategoryId = new Guid("7d8e9f0a-1122-3344-5566-778899aabbcc"),
                            ProductDescription = "หมอนเมมโมรี่โฟมเพื่อสุขภาพ ออกแบบตามหลักสรีรศาสตร์ รองรับต้นคอและบ่าได้อย่างพอดี ช่วยลดอาการปวดเมื่อยขณะนอนหลับ ปลอกหมอนผ้าทอจากเส้นใยไม้ไผ่ธรรมชาติ นุ่มสบาย ระบายอากาศได้ดี",
                            ProductName = "ErgoComfort Memory Foam Pillow",
                            ProductPrice = 1590.00m
                        });
                });

            modelBuilder.Entity("Store.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2b6fb1a-4c28-4b71-a02d-ff14b986e3a1"),
                            Password = "$2a$11$8l5uer78GXrq6Hl6Py8v.e3qOisnxDbVOZW/prHQombzmJmvrw6Du",
                            Role = "admin",
                            Username = "admin001"
                        },
                        new
                        {
                            Id = new Guid("e8fa47c3-3b1a-4f92-96d5-cc2140a7b532"),
                            Password = "$2a$11$fW2zVTrDAiOLpOe2xsoB1uhHjJDonKyRAgeiQM6c7FJC25T1fvxHm",
                            Role = "operation",
                            Username = "operation001"
                        });
                });

            modelBuilder.Entity("Store.Api.Entities.Order", b =>
                {
                    b.HasOne("Store.Api.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Store.Api.Entities.OrderDetail", b =>
                {
                    b.HasOne("Store.Api.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Store.Api.Entities.Product", "Product")
                        .WithMany("OrderDetials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Store.Api.Entities.Product", b =>
                {
                    b.HasOne("Store.Api.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Store.Api.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Store.Api.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Store.Api.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Store.Api.Entities.Product", b =>
                {
                    b.Navigation("OrderDetials");
                });
#pragma warning restore 612, 618
        }
    }
}
